### ISSUE TITLE
Data format changed or data node is wrong leading to funny display

### ISSUE THREAD

**Issue by davidsiska-vega** [vegaprotocol/ticker-service#5]
![image](https://user-images.githubusercontent.com/62546419/160842871-6079a359-5d1a-4731-937b-b5d705303a33.png)

**Comment by barnabee** [comment]
Other statuses look reasonable. It is possible a market never closed before and this is untested.

I suspect a quick fix. Will prod it later.

**Comment by barnabee** [comment]
Fixed https://github.com/vegaprotocol/ticker-service/commit/5abc5ae46048a52391799931d395aca9cb3fc5b9
